[global]
# log-timezone = UTC

# ── Run backup every 4 hours ─────────────────────────────────────────────────
[job-run "postgres-backup"]
schedule  = @every 4h
; schedule = 0 */4 * * *   # cron syntax also works
image     = ghcr.io/quyendv/postgresql-backup:latest
; image   = postgresql-backup:local
network   = postgres-backup_default
env-file  = /opt/postgresql-backup/.env
volume    = postgres-backup_backup_data:/backup
delete    = true
